### ISSUE TITLE
Setting Up URDF Bug

### ISSUE THREAD

**Issue by enyuin** [ros-planning/navigation.ros.org#175]
Under this link, [https://navigation.ros.org/setup_guides/urdf/setup_urdf.html#urdf-and-the-robot-state-publisher](url), there is one bug. The box inertia macro is not defined in this case, and it will cause error while building it. It is suggested to be removed to reduce misunderstanding. 
![bug](https://user-images.githubusercontent.com/13057462/120919966-e4ea2b80-c6ee-11eb-89c9-6508636d332b.png)

**Comment by SteveMacenski** [comment]
The xacro was added below in https://navigation.ros.org/setup_guides/urdf/setup_urdf.html#adding-physical-properties. 


I agree in https://navigation.ros.org/setup_guides/urdf/setup_urdf.html#writing-the-urdf the line 31 should be removed. Can you submit a PR containing that change?
