### ISSUE TITLE
Nav2 Planner Metrics with 

### ISSUE THREAD

**Issue by Opala76** [ros-planning/navigation.ros.org#185]
Hello, 

I am new to ROS and I don't know if this is the right place to ask about this. 
I did research but I couldn't find anything about how to calculate some planner metrics.

I would like to run a wide variety of planners SmacPlanner, A*, Hybrid-A*  and varying some parameters while measuring the time to obtain the global path and its length. For now, I'm clueless about how to do it. 

Additionally,  I would like to set the initial pose and the goal pose programmatically so I can guarantee that the start and final poses are always the same. I do not have this precision using rviz commands. I tried publishing to the topic /initialpose with the following command but without success.

```
ros2 topic pub -1 /initialpose  geometry_msgs/PoseWithCovarianceStamped '{ header: {stamp: {sec: 0, nanosec: 0}, frame_id: "map"}, pose: { pose: {position: {x: 10, y: 10.0, z: 00.0}, orientation: {w: 0.1}}, } }'
```

Said that I have the following questions:

1. Is there a topic that I can subscribe in order to get those metrics (path length and average time to compute global path)?
2. Is the initialpose the correct topic to publish this pose? Which topic can I use to publish the goal pose? I tried the /goal_pose but also without success.

**Comment by SteveMacenski** [comment]
ROS Answers would be your best bet, but really you should consult literature and API documentation.
