### ISSUE TITLE
Url Dead

### ISSUE THREAD

**Issue by vkuehn** [ros-planning/navigation.ros.org#198]
On https://navigation.ros.org/getting_started/index.html the Link to the "Official Turtlebot" totorial ends up in 404 for 
https://emanual.robotis.com/docs/en/platform/turtlebot3/ros2_setup/

Not sure what file here would have to be changed.

**Comment by SteveMacenski** [comment]
A pr to fix would be appreciated

**Comment by vkuehn** [comment]
AS I am 
Not sure what file here would have to be changed.
AND
If the turtlebot people enlighten us where the ros2 documentation is?

I could do that

**Comment by SteveMacenski** [comment]
https://github.com/ros-planning/navigation.ros.org/pull/199

**Comment by vkuehn** [comment]
thanks for your activity !
