### ISSUE TITLE
Regulated Pure Pursuit controller documentation - max_angular_accel units is m/s/s

### ISSUE THREAD

**Issue by Mohit-Ak** [ros-planning/navigation.ros.org#207]
I was reading through the documentation of Regulated Pure Pursuit Controller and bumped onto the field called `max_angular_accel` with the unit as `m/s/s`. 

[Screenshot](https://drive.google.com/file/d/1oi9XRsfsPgyIe76rSHQHLdPdcpGfiulR/view?usp=sharing)

I don't know if this is correct or if it has to be `rad/s/s`?

https://navigation.ros.org/configuration/packages/configuring-regulated-pp.html

**Comment by SteveMacenski** [comment]
m/s^2 in a really esoteric way because apparently I was asleep at the keyboard

**Comment by SteveMacenski** [comment]
Fixed
