### ISSUE TITLE
Updating the parameters in the config guidelines

### ISSUE THREAD

**Issue by Marwan99** [ros-planning/navigation.ros.org#21]
List of parameters with their state (https://github.com/ros-planning/navigation2/blob/master/doc/parameters/param_list.md):
- [x] bt_navigator
- [x] costmaps
- [x] DWB
- [x] waypoint follower 
- [x] controller_server
- [x] lifecycle_manager
- [x] map_server
- [x] planner_server
- [x] navfn_planner
- [x] recoveries
- [x] AMCL
- [x] Behavior Tree Nodes

**Comment by SteveMacenski** [comment]
@Marwan99 I'm going to do the lifecycle manager and waypoint follower right now

**Comment by SteveMacenski** [comment]
And controller server, because I had a few minutes to kill

**Comment by Marwan99** [comment]
@SteveMacenski I will have a go at the bt nodes.

**Comment by SteveMacenski** [comment]
My plan today was the planner server and navfn plugin.

**Comment by SteveMacenski** [comment]
Also did mapserver

**Comment by SteveMacenski** [comment]
Once we're done with all of them, we should remove the tunable parameters page since it will be unnecessary

**Comment by SteveMacenski** [comment]
recoveries done... OK done for the day for real now

**Comment by SteveMacenski** [comment]
I'll do AMCL tomorrow. You mind taking DWB and the costmaps?

**Comment by SteveMacenski** [comment]
Eh, I'll do AMCL right now. Which would you rather do; DWB or costmaps? I'll do the other.

**Comment by Marwan99** [comment]
I go with DWB.

**Comment by SteveMacenski** [comment]
*phew* I wanted to do costmaps so that's a good fit :laughing:

**Comment by SteveMacenski** [comment]
Sweet, we might be done with this by the end of the week. That would be great. I'll post on discourse about it once we're done.

**Comment by SteveMacenski** [comment]
@Marwan99 when you're done, remember to delete the existing DWB pages and the "tuning the controller' page
