### ISSUE TITLE
Update the list of Plugins for the SMAC planner

### ISSUE THREAD

**Issue by padhupradheep** [ros-planning/navigation.ros.org#215]
Using the configs from the documentation leads to the following error:

`Failed to create global planner. Exception: According to the loaded plugin descriptions the class nav2_smac_planner/SmacPlanner with base class type nav2_core::GlobalPlanner does not exist. Declared types are  nav2_navfn_planner/NavfnPlanner nav2_smac_planner/SmacPlanner2D nav2_smac_planner/SmacPlannerHybrid nav2_theta_star_planner/ThetaStarPlanner`

There are 2 possible options:  `nav2_smac_planner/SmacPlanner2D` and `nav2_smac_planner/SmacPlannerHybrid ` 
Also Reeds-Shepp is only supported in the `nav2_smac_planner/SmacPlannerHybrid `  

I'm not sure about the other motion models. 

I will test it and give a PR!

**Comment by SteveMacenski** [comment]
https://navigation.ros.org/plugins/index.html

I believe it is updated, can you point to somewhere specific so I know where to update?
