### ISSUE TITLE
Example new costmap2d plugin is confusing

### ISSUE THREAD

**Issue by Mickboe1** [ros-planning/navigation.ros.org#248]
The current version of writing new costmap2d plugins shows an example that overrides the master grid. A proper example of how to add cost in a separate costmap is not included. the current version basically shows what not to do and is confusing.

https://navigation.ros.org/plugin_tutorials/docs/writing_new_costmap2d_plugin.html#writing-new-costmap2d-plugin

**Comment by SteveMacenski** [comment]
Some concrete suggestion would be nice. We do spend quite a bit of time building these tutorials (and no one's specifically paying or telling us to) so if you have some tangible suggestion, we'd be happy to hear it. 

Here are several real places where the master grid is updated in the real plugins you really use, so I'm not sure where you get the notion that you're "not supposed to do that": 

- https://github.com/ros-planning/navigation2/blob/30b405c58e6d53ba8c96381416bc4679d35a1483/nav2_costmap_2d/src/costmap_layer.cpp#L129-L133
- https://github.com/ros-planning/navigation2/blob/30b405c58e6d53ba8c96381416bc4679d35a1483/nav2_costmap_2d/plugins/inflation_layer.cpp#L266-L273
- https://github.com/ros-planning/navigation2/blob/fc2c70a6df17595aaafc5de760a5f29c1e327738/nav2_costmap_2d/plugins/costmap_filters/keepout_filter.cpp#L286-L288
- https://github.com/ros-planning/navigation2/blob/30b405c58e6d53ba8c96381416bc4679d35a1483/nav2_costmap_2d/plugins/range_sensor_layer.cpp#L505-L508
