### ISSUE TITLE
pure pursuit use_velocity_scaled_lookahead_dist

### ISSUE THREAD

**Issue by joe28965** [ros-planning/navigation.ros.org#250]
On the website on [this page](https://navigation.ros.org/configuration/packages/configuring-regulated-pp.html) the `use_velocity_scaled_lookahead_dist` is said to have the default `double` of `0.4`. That should just be a `bool` set to `false` right?
I think it's this [github page](https://github.com/ros-planning/navigation.ros.org/blob/master/configuration/packages/configuring-regulated-pp.rst) that should be edited to update the `use_velocity_scaled_lookahead_dist` right?

I'm not 100% sure if the default is set to `false` though.

**Comment by SteveMacenski** [comment]
That is correct- can you submit a PR to fix?

**Comment by joe28965** [comment]
done. PR #251
