### ISSUE TITLE
Can I ask a question that how to debug when I am writing a planner plugin? This is important to me, and I'm wishing to get an answer.

### ISSUE THREAD

**Issue by Lindsay284** [ros-planning/navigation.ros.org#262]

**Comment by SteveMacenski** [comment]
Likely not, we only help on open source extensions. If this is a proprietary project, we don't offer assistance. If this is something you would consider paid help for, you can find my email on my profile and if you give me some context, I can see who might be the most appropriate person to connect you too for consulting/contracting.
