### ISSUE TITLE
Not able to build on 22.04

### ISSUE THREAD

**Issue by padhupradheep** [ros-planning/navigation.ros.org#319]
Something is fishy, when I try to build on ubuntu 22.04

```
WARNING: Invalid configuration value found: 'language = None'. Update your configuration to a valid langauge code. Falling back to 'en' (English).

Exception occurred:
  File "/home/pradheep/.local/lib/python3.10/site-packages/breathe/node_factory.py", line 5, in <module>
    import sphinx.ext.mathbase
ModuleNotFoundError: No module named 'sphinx.ext.mathbase'
The full traceback has been saved in /tmp/sphinx-err-v_0nnovb.log, if you want to report the issue to the developers.
```

I'll check for the issue and will give a PR..

**Comment by SteveMacenski** [comment]
Did you not install all necessary dependencies? It looks like `mathbase` just needs to be installed?

**Comment by padhupradheep** [comment]
but it should be installed as part of the sphinx core right?

That is what the documentation says: https://www.sphinx-doc.org/en/master/usage/extensions/math.html

**Comment by padhupradheep** [comment]
So, the solution would be to use breathe 4.28.0 ! I'll give a PR after testing it on 20.04 as well
