### ISSUE TITLE
Tutorial improvement: Avoid hardcoding build type

### ISSUE THREAD

**Issue by tfoote** [ros-planning/navigation.ros.org#329]
The profiling tutorial recommends hardcoding embedding the debug information into the CMakeLists.txt

This is typically better to not hardcode compile settings ([like this](https://github.com/ros-planning/navigation.ros.org/pull/328/files#diff-e4ca88f8dc3fb442289e4cf7bc9e2237a543beeb7d98b77d4ee283ddedceb2e9R37) )and require changes to the source code, but to instead set this when building. For example if you accidentially force debug on in CMakeLists.txt it can cause unexpected results when people try to do full release builds in a different worksapce

You could instead instruct people how to set the CMake variable [`CMAKE_BUILD_TYPE` variable](https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html#variable:CMAKE_BUILD_TYPE) To something such as `RelWithDebInfo` from the standard list of build types: https://cmake.org/cmake/help/latest/manual/cmake-buildsystem.7.html#default-and-custom-configurations 

If this doesn't work that's fine, but it also avoids the complexity of having to know exactly where to insert the option too.  

Another option is to set the CXX_FLAGS at compile time too https://stackoverflow.com/a/40922025/604099

**Comment by SteveMacenski** [comment]
https://github.com/ros-planning/navigation.ros.org/pull/330 

Thanks!
