### ISSUE TITLE
Instruction for "Getting Started" does not work for any of the current ROS 2 versions (as of 2020/07/02)

### ISSUE THREAD

**Issue by GuanyangLuo** [ros-planning/navigation.ros.org#36]
For `Foxy` and `Eloquent`, `sudo apt install ros-<ros2-distro>-turtlebot3*` does not work because there are no turtlebot3 releases for those distros (yet).

For `Dashing`, `ros2 launch nav2_bringup tb3_simulation_launch.py` does not work because `tb3_simulation_launch.py` does not exist for `Dashing`. I believe it only exist for the master branch right now.

**Comment by SteveMacenski** [comment]
File a ticket on turtlebot3 for releases. https://github.com/ROBOTIS-GIT/turtlebot3/issues/561 https://github.com/ROBOTIS-GIT/turtlebot3/issues/599, I've also tried. On that topic, we have no control, that's under ROBOTIS' projects. 

That launch file has been well documented in tickets / ros answers to have changed. Check migration guides, we only support docs on the most recent version
