### ISSUE TITLE
Documentation: Bug in 'Setting Up Odometry'

### ISSUE THREAD

**Issue by smnhdw** [ros-planning/navigation.ros.org#468]
In the documentation (https://navigation.ros.org/setup_guides/odom/setup_odom.html#launch-and-build-files) it's mentioned to delete everything related to 'GUI'. Doing that, following lines are messing up the console:
```
[rviz2-6] Warning: Invalid frame ID "drivewhl_l_link" passed to canTransform argument source_frame - frame does not exist
[rviz2-6]          at line 133 in /tmp/binarydeb/ros-foxy-tf2-0.13.14/src/buffer_core.cpp
[...]
[rviz2-6] Warning: TF_OLD_DATA ignoring data from the past for frame drivewhl_r_link at time 0.360000 according to authority Authority undetectable
[rviz2-6] Possible reasons are listed at http://wiki.ros.org/tf/Errors%20explained
[rviz2-6]          at line 332 in /tmp/binarydeb/ros-foxy-tf2-0.13.14/src/buffer_core.cpp
[rviz2-6] Warning: TF_OLD_DATA ignoring data from the past for frame drivewhl_l_link at time 0.360000 according to authority Authority undetectable
[rviz2-6] Possible reasons are listed at http://wiki.ros.org/tf/Errors%20explained
[rviz2-6]          at line 332 in /tmp/binarydeb/ros-foxy-tf2-0.13.14/src/buffer_core.cpp
[ekf_node-5] Warning: TF_OLD_DATA ignoring data from the past for frame drivewhl_r_link at time 0.360000 according to authority Authority undetectable
[ekf_node-5] Possible reasons are listed at http://wiki.ros.org/tf/Errors%20explained
```
Furthermore, the later proposed command  'ros2 run tf2_ros tf2_echo odom base_link' is also just showing following output:

```
Warning: TF_OLD_DATA ignoring data from the past for frame drivewhl_l_link at time 14.401000 according to authority Authority undetectable
Possible reasons are listed at http://wiki.ros.org/tf/Errors%20explained 
       at line 332 in /tmp/binarydeb/ros-foxy-tf2-0.13.14/src/buffer_core.cpp
```

Looking into your final launch file (https://github.com/ros-planning/navigation2_tutorials/blob/master/sam_bot_description/launch/display.launch.py#L45), the GUI parameter is still existing and the launch condition of the joint_state_publisher_node is still provided.
Adding that again, the aforementioned behavior isn't there anymore and 'ros2 run tf2_ros tf2_echo odom base_link' shows the correct output.

Things to adapt on documentation:
- Only remove 'joint_state_publisher_gui_node' from launch/display.launch.py

Additionally, mention that 
```
launch.actions.ExecuteProcess(cmd=['gazebo', '--verbose', '-s', 'libgazebo_ros_init.so', '-s', 'libgazebo_ros_factory.so'], output='screen'),
```
has to be added to the 'launch/display.launch.py' file. This might be obvious for advanced ROS users, but not for beginners. The following sentence "Open launch/display.launch.py again [...]" is also quite misleading in this regard.

**Comment by SteveMacenski** [comment]
> Looking into your final launch file (https://github.com/ros-planning/navigation2_tutorials/blob/master/sam_bot_description/launch/display.launch.py#L45), the GUI parameter is still existing and the launch condition of the joint_state_publisher_node is still provided.

Yes, but if its not set, then we use the robot staet publisher from https://github.com/ros-planning/navigation2_tutorials/blob/master/sam_bot_description/launch/display.launch.py#L21

>   Only remove 'joint_state_publisher_gui_node' from launch/display.launch.py

But OK! Can you open a PR to make that change? I'd love for you to get credit for your debugging!

**Comment by SteveMacenski** [comment]
Mass update to docs shortly will address
