### ISSUE TITLE
Friction on Caster Link

### ISSUE THREAD

**Issue by callen5914** [ros-planning/navigation.ros.org#494]
I tried to implement a change to the xacro file by reducing the friction on the caster because the robot travels in the direction of the caster it jumps really bad in Gazebo... Even with 0.0 values, it still jumps pretty bad. 

Anyone else getting this behavior?
`<surface>
                <friction>
                    <ode>
                        <mu>0.0</mu>
                        <mu2>0.0</mu2>
                    </ode>
                </friction>
            </surface>
`

**Comment by SteveMacenski** [comment]
That seems like something better to take up with the gazebo folks potentially

**Comment by callen5914** [comment]
Fair enough... I figured if the docs proposed this URDF as a good start to use for learning the package it would function better... After all how good can nav be if your sensors can't reliably sense that environment...
