### ISSUE TITLE
urdf not passed to joint_state_publisher

### ISSUE THREAD

**Issue by Omar-Salem** [ros-planning/navigation.ros.org#508]
In [First-Time Robot Setup Guide](https://navigation.ros.org/setup_guides/index.html), the urdf file path is not passed to the `joint_state_publisher_node`, leading to error **No transform from [drivewhl_l_link] to [odom]**

![Screenshot from 2024-01-14 07-45-58](https://github.com/ros-planning/navigation.ros.org/assets/2016944/6aba8318-dd67-47d6-8233-64dea980e7f5)

**Comment by SteveMacenski** [comment]
Thanks!
