### ISSUE TITLE
URL in writing_new_navigator_plugin is wrong

### ISSUE THREAD

**Issue by Ericsii** [ros-planning/navigation.ros.org#543]
https://github.com/ros-planning/navigation.ros.org/blob/55f8a1b5f5c97515eb6b1b8df3c0186dadce0702/plugin_tutorials/docs/writing_new_navigator_plugin.rst?plain=1#L33

The URL link `https://github.com/ros-planning/navigation2/nav2_bt_navigator` for `Nav2's BT Navigator package` is 404. I think this should be changed to `https://github.com/ros-planning/navigation2/tree/main/nav2_bt_navigator`

**Comment by SteveMacenski** [comment]
Huh, odd. Can you submit a PR?
