### ISSUE TITLE
Pushes to master kill the CNAME file

### ISSUE THREAD

**Issue by SteveMacenski** [ros-planning/navigation.ros.org#6]
Need to change the CircleCI workflow on publishing to make sure we don't nuke the CNAME file (or recreate it each time) in the `gh-pages` deployment branch.

This file is required so the website is hosted on `navigation.ros.org` vs `ros-planning.github.io/navigation.ros.org`.

**Comment by crdelsey** [comment]
I'll fix this along with the move to root fix.
