### ISSUE TITLE
Add UBR-1 to Robots using webpage

### ISSUE THREAD

**Issue by SteveMacenski** [ros-planning/navigation.ros.org#74]
As @mikeferguson has so kindly leveraged this tool in his rehabilitation of Sparky (or whatever you named it :wink: )

**Comment by mikeferguson** [comment]
I assigned myself - I'll open a PR shortly

**Comment by SteveMacenski** [comment]
Any update on that @mikeferguson :smiley:

**Comment by mikeferguson** [comment]
Tuesday. I'm planning to have the blog post up Tuesday (it's a beast - there's lots of detail of what/how I set things up). Once I've got that up, I'll open a PR.

**Comment by mikeferguson** [comment]
Oh - and I'll actually have a nav2 on UBR-1 demo at Bots and Beers this week

**Comment by mikeferguson** [comment]
#81
