### ISSUE TITLE
DWB page is not up to date after checker refactors

### ISSUE THREAD

**Issue by mikeferguson** [ros-planning/navigation.ros.org#80]
https://navigation.ros.org/configuration/packages/configuring-dwb-controller.html

The sample at the bottom of the page is not up to date after the progress/goal checkers have been pulled out into separate plugins.

**Comment by SteveMacenski** [comment]
@siddhya from PR https://github.com/ros-planning/navigation2/pull/1857 can you make these updates? They were made in the md file `param_list.md` but not then in this repo for the documentation.
