### ISSUE TITLE
Tutorial: Using smac planner

### ISSUE THREAD

**Issue by SteveMacenski** [ros-planning/navigation.ros.org#97]

**Comment by mag-seasony** [comment]
Concerning Smac, in the docs, more precisely in the example, the plugin name is incorrect (file navigation.ros.org/configuration/packages/configuring-smac-planner.rst line 386) instead of "nav2_smac_planner/SmacPlanner" it should be "smac_planner/SmacPlanner"

**Comment by SteveMacenski** [comment]
A PR would be appreciated

**Comment by mag-seasony** [comment]
done
